[build]
  publish = "dist"
  command = "npm run build"

[build.environment]
  NODE_VERSION = "18"
  # Safety: avoid peer-deps resolution failures in Netlify CI
  NPM_FLAGS = "--legacy-peer-deps --no-audit --no-fund"

# Enable Netlify Blobs
[functions]
  node_bundler = "esbuild"

# Redirect rules for SPA
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  conditions = {Role = ["admin"], Country = ["US"]}

# Basic redirects
[[redirects]]
  from = "/KI/*"
  to = "/:splat"
  status = 200


